### ISSUE TITLE
project structure & folder structure

### ISSUE THREAD

**Issue by rvitaliy** [doctrine-extensions/doctrine-extensions#8]
### Project structure
I open this discussion to suggest organizing this project designed more for micro-vendors.
`Sluggable` > `doctrine-extensions/sluggable`
`Timestampable` > `doctrine-extensions/timestampable`
`etc` > `doctrine-extensions/etc`
all this things are independent.
it's easier to main and evolve single project

### Folder structure
Please split `src` and `tests` in two separate folder
it's easier to understand and to include/exclude from autoloading.

**Comment by Padam87** [comment]
Hi @rvitaliy,

Thank you for taking the time to look at this project.

The organization is already very similar to what you suggest. Each extension has its own repo, and there is a common repo.

This is the main monorepo for this project, where we work. A subtree split ensures the individual component's updates. (ala Symfony)

As for the tests... those will probably stay where they are for the time being. These type of questions are just time wasters until we don't have the contributors necessary for this project. If we find people willing to help out we will discuss this, amongst a couple of other decisions mentioned by others.

**Comment by AkenRoberts** [comment]
Thank you for the comment @rvitaliy. We have a pretty good idea of how we'll be laying things out if and when things get off the ground. Cheers!
